### ISSUE TITLE
Infinite Damage Indicator While Sitting on Certain Furniture

### ISSUE THREAD

**Issue by madebygood** [Insprill/damage-indicator#27]
Describe the bug
When sitting on certain furniture created using ItemsAdder, the damage indicator keeps showing repeatedly as if the player is taking infinite damage. However, no actual damage is applied to the player. It seems that only ItemsAdder "thinks" the player is taking damage.

To Reproduce

Place a furniture item (e.g., a chair) that has a solid block directly above the sitting area.

Sit on the furniture.

Observe the repeated damage animation and sound.

Expected behavior
Players should be able to sit on any furniture without triggering the damage animation or indicator unless actual damage is being dealt.

Screenshots
![Image](https://github.com/user-attachments/assets/c9b019c6-226b-43dc-94e4-c59259f66f02)

![Image](https://github.com/user-attachments/assets/c3966058-26ef-4b10-bc2a-7f640f9de25c)

Additional context
This doesn't seem to happen with all furniture. Based on testing, it likely occurs when the furniture has a solid block above it (e.g., a ceiling or enclosed top part).
No health is lost, and no damage event is triggered by other plugins—only ItemsAdder seems to misinterpret it as damage.

Server Info
ItemsAdder version: 3.6.6

Minecraft version: 1.20.1

DamgeIndicator version : 1.17.0

**Comment by Insprill** [comment]
I don't have ItemsAdder to test with, however, I implemented a potential fix in https://github.com/Insprill/damage-indicator/commit/c5a79af2f01ace8550d83b62ed7fcab89ca5c597. I just released v1.18.0 with that commit, so please try it out and let me know if it fixed the issue or not.

**Comment by madebygood** [comment]
After updating to version 1.18.0, the issue seems to have become more noticeable.

The problem where unlimited damage is displayed when sitting on a chair still persists.

A new issue has been observed: even in protected zones where PvP is disabled, the damage indicator still appears when a player is hit. This behavior was not present in version 1.17.0.

It might be that the detection has become a bit too sensitive in some situations, possibly reacting to things that weren't intended. Just wanted to share this in case it helps with further improvements.

**Comment by Insprill** [comment]
That makes no sense at all. What plugin do you use for protected zones?
